# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm --no-git-tag-version version 0.0.$(Build.BuildId)
    echo _auth = 0d24f2be-0d03-4932-9f41-0fa748ea93b5 > ~/.npmrc
    echo email = bsmithb2@gmail.com >> ~/.npmrc
    echo 'starting npm install'
    npm install
    gulp build
    npm run publish-please
  displayName: 'npm install and run gulp'
